
# services:
#   elastic:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
#     container_name: elastic
#     environment:
#       - cluster.name=docker-cluster
#       - bootstrap.memory_lock=true
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1
#     volumes:
#       - esdata1:/usr/share/elasticsearch/data
#     ports:
#       - 9200:9200
#     networks:
#       - development

#   # kibana:
#   #   image: docker.elastic.co/kibana/kibana
#   #   container_name: kibana
#   #   ports:
#   #     - 5601:5601
#   #   environment:
#   #     ELASTICSEARCH_URL: http://elastic:9200
#   #   networks:
#   #     - elastic

# volumes:
#   esdata1:
#     driver: local

# networks:
#   development:
#     driver: bridge


services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elastic
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic_network

volumes:
  esdata:
    driver: local

networks:
  elastic_network:
    driver: bridge
