global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'app'

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

# # job for seeing the metrics from cadvisor,
# # so we can see the cpu and memory usage of the containers
#   - job_name: 'cadvisor'            
#     static_configs:
#       - targets: ['cadvisor:8080']   


  - job_name: 'node_exporter'  
    static_configs:
      # - targets: ['node_exporter:9100']
      - targets: ['127.0.0.1:9100']
      

  - job_name: 'docker'  # container metrics
    static_configs:
      - targets: ['127.0.0.1:9323'] 